export const voiceMetaData = {
    knox: {
        name: "knox",
        id: "r6h5YavIGu0wZzg5gkkN",
        stability: 0.45,
        similarity_boost: 0.95,
        style: 0,
        // use_speaker_boost: true,
        model_id: "eleven_multilingual_v2",
    },
    vilkrin: {
        name: "vilkrin",
        id: "3s66e8hLZV2BDy5iH0PU",
        stability: 0.75,
        similarity_boost: 0.75,
        style: 0,
        // use_speaker_boost: true,
        model_id: "eleven_multilingual_v2",
    },
    germanMario: {
        name: "germanMario",
        id: "j9jnXcYTprJBiRnYU55H",
        stability: 0.60,
        similarity_boost: 0.90,
        style: 0,
        // use_speaker_boost: true,
        model_id: "eleven_multilingual_v2",
    },
    animeGirl: {
        name: "animeGirl",
        id: "FlO6X7dwvuIXITz4AqFf",
        stability: 0.55,
        similarity_boost: 0.45,
        style: 0,
        // use_speaker_boost: true,
        model_id: "eleven_multilingual_v2",
    },
    lucia: {
        name: "lucia",
        id: "YNgirr5gSP95qX8FxNui",
        stability: 0.75,
        similarity_boost: 0.45,
        style: 0,
        // use_speaker_boost: true,
        model_id: "eleven_multilingual_v2",
    },
} 
// export const voiceMetaData = {
//     knox: {
//         name: "knox",
//         id: "r6h5YavIGu0wZzg5gkkN",
//         stability: 0.45,
//         similarity_boost: 0.95,
//         model_id: "eleven_monolingual_v1",
//     },
//     vilkrin: {
//         name: "vilkrin",
//         id: "3s66e8hLZV2BDy5iH0PU",
//         stability: 0.75,
//         similarity_boost: 0.75,
//         model_id: "eleven_monolingual_v1",
//     },
//     germanMario: {
//         name: "germanMario",
//         id: "j9jnXcYTprJBiRnYU55H",
//         stability: 0.60,
//         similarity_boost: 0.90,
//         model_id: "eleven_monolingual_v1",
//     },
//     animeGirl: {
//         name: "animeGirl",
//         id: "FlO6X7dwvuIXITz4AqFf",
//         stability: 0.55,
//         similarity_boost: 0.45,
//         model_id: "eleven_monolingual_v1",
//     },
//     lucia: {
//         name: "lucia",
//         id: "YNgirr5gSP95qX8FxNui",
//         stability: 0.75,
//         similarity_boost: 0.45,
//         model_id: "eleven_monolingual_v1",
//     },
// } 