version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BrokenGmBotVoices"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jqxpeg9n3vst"
s3_prefix = "BrokenGmBotVoices"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
